### PR TITLE
fix download button in posted as image

### PR DESCRIPTION
**Pull request by rodcotines**
Before
image

After

image

### CODE REVIEW

**Review by tfudoinkebs — APPROVED** [review]
LGTM!

**Review by bricesuazo — COMMENTED** [review]
Can you make it just full width?

**Comment by rodcotines** [comment]
Wdym, i'll check on it later

**Comment by bricesuazo** [comment]
> Wdym, i'll check on it later

image

**Comment by rodcotines** [comment]
> > Wdym, i'll check on it later
> 
> image
On it

**Comment by rodcotines** [comment]
Done @bricesuazo

**Review by bricesuazo — APPROVED** [review]

**Pull request merged**
