### PR TITLE
Implement strikes, ban, deactivate, and reactivate account

### PR DESCRIPTION
**Pull request by bricesuazo**
Make sure to `pnpm migration:up` first before testing this PR.

Implemented strikes, ban, deactivate, and reactivate account in account settings.

### CODE REVIEW

**Review by aaronjoshuaespinosa — COMMENTED** [review]
Strikes screen working properly, displaying strikes count.
image
image

4/3 strikes, still not banned
image

When banned is applied, session is not deleted, not redirected to landing page
image


Input placeholder in deactivate modal can be changed into user's own username
image

Deactivated account notice properly showing (nice!)
image

Reactivate screen showing properly (nice!)
image

**Comment by bricesuazo** [comment]
> Strikes screen working properly, displaying strikes count. image image
> 
> 4/3 strikes, still not banned image
> 
> When banned is applied, session is not deleted, not redirected to landing page image
> 
> Input placeholder in deactivate modal can be changed into user's own username image
> 
> Deactivated account notice properly showing (nice!) image
> 
> Reactivate screen showing properly (nice!) image

All good!

**Comment by aaronjoshuaespinosa** [comment]
Error in ban resolved by clearing cookies.

Error card should have a background for proper visibility
image

**Review by rodcotines — APPROVED** [review]
Nice!

**Review by aaronjoshuaespinosa — APPROVED** [review]
nice work! keep up the good work!

**Pull request merged**
