### PR TITLE
Header and chats indicator

### PR DESCRIPTION
**Pull request by bricesuazo**
run `pnpm migration:up` first,

- Added indicator for unread chats and posts

This PR also fixed this issue: https://github.com/bricesuazo/kabsu.me/issues/125

Demo:

https://github.com/user-attachments/assets/e9b06395-a4df-41ed-a257-738dbbe1181f

### CODE REVIEW

**Review by tfudoinkebs — CHANGES_REQUESTED** [review]
Everything else is working, except for the count indicator in the header. It's functioning, but in mobile view, the icons disappear.
image

**Comment by bricesuazo** [comment]
> Everything else is working, except for the count indicator in the header. It's functioning, but in mobile view, the icons disappear. image

What do you think is the fix here @aaronjoshuaespinosa?

**Comment by rodcotines** [comment]
User bug, current user name is being displayed instead of the other user 
image

**Review by AlexisKenAlvarez — COMMENTED** [review]
Instead of removing the icon when there is a new unread post on mobile view. Just copy the notification indicator for the notification to keep the indicator and icon both visible.
image

Like this
image

**Comment by bricesuazo** [comment]
> User bug, current user name is being displayed instead of the other user image

Fixed.

**Comment by bricesuazo** [comment]
> Instead of removing the icon when there is a new unread post on mobile view. Just copy the notification indicator for the notification to keep the indicator and icon both visible. image
> 
> Like this image

How about something like this?

image
image

**Comment by AlexisKenAlvarez** [comment]
LGTM but I have minor concern, maybe we can use the size of green circle like the one on notification because the one on header looks slightly bigger, and also put it on the top right of the icon just like the notification just for consistency
image

**Review by tfudoinkebs — APPROVED** [review]
LGTM!

**Pull request merged**
