### PR TITLE
Feat/add better mention

### PR DESCRIPTION
**Pull request by AlexisKenAlvarez**
Added better mention, still needed more testing, expect bugs

### CODE REVIEW

**Comment by rodcotines** [comment]
please fix pnpm-lock.yaml

**Review by bricesuazo — COMMENTED** [review]
This is nice.

Just have some minor points:
- Fix the conflicting files.
- Add `POST_MENTION_SECRET` to .env.example.
- Fix post form input in dark mode.
image

**Review by bricesuazo — COMMENTED** [review]
I'm not sure why but I'm still getting an `@anonymous_user` when I mention users.
image


Also, can we remove the username in the post content? Since it's changeable.
image

**Comment by bricesuazo** [comment]
Can we use https://www.npmjs.com/package/lodash.debounce for debounce?

**Review by aaronjoshuaespinosa — COMMENTED** [review]
nice mention feature!

**Review by bricesuazo — APPROVED** [review]

**Pull request merged**
